<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="javascript:void(0);">站点设置</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            站点设置
            <small>
                <i class="icon-double-angle-right"></i>
                阅读设置
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <form action="{{url('options/saveread')}}" method="post" class="form-horizontal" id="saveread-options-form">
            <div class="form-group">
                <label for="page-article-name" class="col-sm-2 control-label">每页文章数</label>
                <div class="col-sm-8">
                    <input type="text" name="pageNum" value="{% if options is not empty %}{{options['page_article_number']['op_value']}}{% endif %}"
                           class="form-control" id="page-article-name" placeholder="请填写每页文章数量">
                    <span class="form-tips">此数目用于指定前台页面每页显示的文章数目</span>
                </div>
            </div>
            <div class="form-group ">
                <label for="recommend-article-number" class="col-sm-2 control-label">推荐阅读文章数目</label>
                <div class="col-sm-8">
                    <input type="text" name="recommendNum" value="{% if options is not empty %}{{options['recommend_article_number']['op_value']}}{% endif %}"
                           class="form-control" id="recommend-article-number" placeholder="请填写推荐阅读显示的文章列表数目">
                    <span class="form-tips">此数目用于指定前台页面中“推荐阅读”栏显示的文章列表数目</span>
                </div>
            </div>
            <div class="form-group ">
                <label for="relate-article-number" class="col-sm-2 control-label">关联文章数目</label>
                <div class="col-sm-8">
                    <input type="text" name="relateNum" value="{% if options is not empty %}{{options['relate_article_number']['op_value']}}{% endif %}"
                           class="form-control" id="relate-article-number" placeholder="请填写关联显示的文章列表数目">
                    <span class="form-tips">此数目用于文章详情页的“你可能感兴趣”的文章列表数目</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <button type="submit" id="read-options-btn" class="btn btn-info btn-sm">保存设置</button>
                </div>
            </div>
        </form>
    </div>
</div>