<div id="colophon">
    <div id="site-info" class="site-info">
        <a href="javascript:void(0)" onClick="goRoll(0)" id="goTop">返回顶部</a> &nbsp;
        <a href="http://www.miitbeian.gov.cn/" rel="external nofollow">粤ICP备13067234号</a>
        <script>

        </script>
        ©2012-2016 <a href="{{siteUrl}}" rel="index" title="Marser">Marser</a> |
        <a href="https://github.com/KevinJay/PhalconCMS" target="_blank" title="PhalconCMS">PhalconCMS</a>
    </div>
</div>
<script type='text/javascript' src='{{ static_url("assets/js/wp-embed.min.js?_v=")~assetsVersion }}'></script>
<div id="float">
    <a id="float_gotop" class="floatbtn" href="javascript:void()" onClick="goRoll(0)" title="返回顶部"></a>
    <a id="float_goend" class="floatbtn" href="javascript:void()" onClick="goend()" title="转到底部"></a>
</div>

<script src='{{ static_url("highlight/scripts/highlight.min.js?_v=")~assetsVersion }}'></script>
<script >hljs.initHighlightingOnLoad();</script>