<meta name="viewport" content="width=device-width , initial-scale=1.0 , user-scalable=0 , minimum-scale=1.0 , maximum-scale=1.0"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>{{siteName}}-{{siteTitle}}</title>
<meta name="keywords" content="{{siteKeywords}}">
<meta name="description" content="{{siteDescription}}">
<link rel="shortcut icon" href="/favicon.ico"/>
<script type='text/javascript' src="{{ static_url('assets/js/jquery.js?_v=')~assetsVersion }}"></script>
<script type='text/javascript' src="{{ static_url('assets/js/jquery-migrate.min.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('highlight/scripts/shCore.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('highlight/scripts/shAutoloader.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript">(function () {
        mod_txt = '#';
        adminBar = "" || 0
    })();</script>
<script type="text/javascript" src='{{ static_url("assets/js/frontopen.js?_v=")~assetsVersion }}'></script>
<link rel="stylesheet" type="text/css" media="all" href='{{ static_url("assets/css/style.css?_v=")~assetsVersion }}'/>
<link rel="stylesheet" type="text/css" media="all" href='{{ static_url("assets/css/mobile.css?_v=")~assetsVersion }}'/>
<link rel="stylesheet" href='{{ static_url("highlight/styles/zenburn.min.css?_v=")~assetsVersion }}'>

<!--[if lt IE 9]>
<script src="./home/html5.js"></script><![endif]-->
<link rel="stylesheet" href='{{ static_url("assets/css/font-awesome.min.css?_v=")~assetsVersion }}'>
<!--[if IE 7]>
<link rel="stylesheet" href='{{ static_url("assets/css/font-awesome-ie7.min.css?_v=")~assetsVersion }}'>
<![endif]-->