<ul class="xoxo">
    {% if recommendArticles is not empty %}
        <li id="advancedrandomposts-2" class="widget-container widget_advancedrandomposts">
            <h3 class="widget-title">推荐阅读</h3>
            <ul class="advanced-random-posts">
                {% for rv in recommendArticles %}
                    <li>
                        <a href={{url("article/"~rv['aid']~".html")}} title="{{rv['title']}}" rel="bookmark">
                            {{rv['title']}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endif %}
    {% if categorysList is not empty %}
        <li id="linkcat-360" class="widget-container widget_links"><h3 class="widget-title">分类</h3>
            <ul class='xoxo blogroll'>
                {% for clk, clv in categorysList %}
                    <li>
                        {% if clv['slug'] is not empty %}
                            <a href={{url("category/"~clv['slug']~".html")}} rel="bookmark" title="{{clv['category_name']}}">
                                {{clv['category_name']}}
                            </a>
                        {% else %}
                            <a href={{url("category/"~clv['cid']~".html")}} rel="bookmark" title="{{clv['category_name']}}">
                                {{clv['category_name']}}
                            </a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endif %}
    {% if tagsList is not empty %}
    <li id="tag_cloud-2" class="widget-container widget_tag_cloud">
        <h3 class="widget-title">标签</h3>
        <div class="tagcloud">
            {% for tlk,tlv in tagsList %}
                {% if tlv['slug'] is not empty %}
                    <a href={{url("tag/"~tlv['slug']~".html")}} class='tag-link-{{tlk}}' title="{{tlv['tag_name']}}" rel="bookmark">{{tlv['tag_name']}}</a>
                {% else %}
                    <a href={{url("tag/"~tlv['tid']~".html")}} class='tag-link-{{tlk}}' title="{{tlv['tag_name']}}" rel="bookmark">{{tlv['tag_name']}}</a>
                {% endif %}
            {% endfor %}
        </div>
    </li>
    {% endif %}
<!--    <li id="linkcat-360" class="widget-container widget_links"><h3 class="widget-title">友情链接</h3>-->
<!--        <ul class='xoxo blogroll'>-->
<!--        </ul>-->
<!--    </li>-->
    <li id="siteinfowidget-2" class="widget-container widget_links">
        <h3 class="widget-title">站点统计</h3>
        <ul class="xoxo siteInfo">
            <li>文章总数：{{totalArticle}}篇</li>
            <li>分类总数：{{totalCategory}}个</li>
            <li>标签总数：{{totalTag}}个</li>
        </ul>
    </li>
    <li id="text-5" class="widget-container widget_text">
        <div class="textwidget">
            <script type="text/javascript">
                /*300*250，创建于2013-9-11*/
            </script>
        </div>
    </li>
</ul>