<!DOCTYPE HTML>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <meta name="robots" content="noindex, nofollow">
    <?php echo $this->tag->stylesheetLink("admin/css/normalize.css");?>
    <?php echo $this->tag->stylesheetLink("admin/css/grid.css");?>
    <?php echo $this->tag->stylesheetLink("admin/css/style.css");?>
    <!--[if lt IE 9]>
    <?php echo $this->tag->javascriptInclude("admin/js/html5shiv.js",false);?>
    <?php echo $this->tag->javascriptInclude("admin/js/respond.js",false);?>
    <![endif]-->
</head>
<body>
<!--[if lt IE 9]>
<div class="message error browsehappy" role="dialog">当前网页 <strong>不支持</strong> 你正在使用的浏览器. 为了正常的访问, 请 <a href="http://browsehappy.com/">升级你的浏览器</a></div>
<![endif]-->
