<meta charset="utf-8" />
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="{{ static_url('bootstrap/css/bootstrap.min.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ static_url('ace/css/font-awesome.min.css?_v=')~assetsVersion }}" />
<link href="{{ static_url('assets/css/style.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ static_url('ace/css/ace.min.css?_v=')~assetsVersion }}" />

<script src="{{ static_url('ace/js/jquery-2.0.3.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('bootstrap/js/bootstrap.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('ace/js/ace-extra.min.js?_v=')~assetsVersion }}"></script>
