<!DOCTYPE HTML>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{{title}}</title>

    <!-- 使用url函数转换相关路径 -->
    <?php echo $this->tag->stylesheetLink("http://cdn.staticfile.org/normalize/2.1.3/normalize.min.css",false);?>
    <?php echo $this->tag->stylesheetLink("home/css/grid.css"); ?>
    <?php echo $this->tag->stylesheetLink("home/css/style.css"); ?>

    <!--[if lt IE 9]>
    <?php echo $this->tag->javascriptInclude("http://cdn.staticfile.org/html5shiv/r29/html5.min.js",false);?>
    <?php echo $this->tag->javascriptInclude("http://cdn.staticfile.org/respond.js/1.3.0/respond.min.js",false);?>
    <![endif]-->

    <!-- 通过自有函数输出HTML头部信息 -->
</head>
<body>
<!--[if lt IE 8]>
<div class="browsehappy" role="dialog">当前网页 <strong>不支持</strong> 你正在使用的浏览器. 为了正常的访问, 请 <a href="http://browsehappy.com/">升级你的浏览器</a></div>
<![endif]-->

<header id="header" class="clearfix">
    <div class="container">
        <div class="row">
            <div class="site-name col-mb-12 col-9">
                <a id="logo" href="#">
<!--                    --><?php //if ($this->options->logoUrl): ?>
<!--                        <img src="--><?php //$this->options->logoUrl() ?><!--" alt="--><?php //$this->options->title() ?><!--" />-->
<!--                    --><?php //endif; ?>
<!--                    --><?php //$this->options->title() ?>
                </a>
                <p class="description">{{description}}</p>
            </div>
            <div class="site-search col-3 kit-hidden-tb">
                <form id="search" method="post" action="./" role="search">
                    <label for="s" class="sr-only">搜索关键字</label>
                    <input type="text" name="s" class="text" placeholder="输入关键字搜索" />
                    <button type="submit" class="submit">搜索</button>
                </form>
            </div>
            <div class="col-mb-12">
                <nav id="nav-menu" class="clearfix" role="navigation">
<!--                    <a--><?php //if($this->is('index')): ?><!-- class="current"--><?php //endif; ?><!-- href="--><?php //$this->options->siteUrl(); ?><!--">--><?php //_e('首页'); ?><!--</a>-->
<!--                    --><?php //$this->widget('Widget_Contents_Page_List')->to($pages); ?>
<!--                    --><?php //while($pages->next()): ?>
<!--                        <a--><?php //if($this->is('page', $pages->slug)): ?><!-- class="current"--><?php //endif; ?><!-- href="--><?php //$pages->permalink(); ?><!--" title="--><?php //$pages->title(); ?><!--">--><?php //$pages->title(); ?><!--</a>-->
<!--                    --><?php //endwhile; ?>
                </nav>
            </div>
        </div><!-- end .row -->
    </div>
</header><!-- end #header -->
<div id="body">
    <div class="container">
        <div class="row">



