<div class="col-mb-12 col-offset-1 col-3 kit-hidden-tb" id="secondary" role="complementary">
<!--    --><?php //if (!empty($this->options->sidebarBlock) && in_array('ShowRecentPosts', $this->options->sidebarBlock)): ?>
        <section class="widget">
            <h3 class="widget-title">最新文章</h3>
            <ul class="widget-list">
<!--                --><?php //$this->widget('Widget_Contents_Post_Recent')
//                    ->parse('<li><a href="{permalink}">{title}</a></li>'); ?>
            </ul>
        </section>
<!--    --><?php //endif; ?>

<!--    --><?php //if (!empty($this->options->sidebarBlock) && in_array('ShowRecentComments', $this->options->sidebarBlock)): ?>
        <section class="widget">
            <h3 class="widget-title">最近回复</h3>
            <ul class="widget-list">
<!--                --><?php //$this->widget('Widget_Comments_Recent')->to($comments); ?>
<!--                --><?php //while($comments->next()): ?>
<!--                    <li><a href="--><?php //$comments->permalink(); ?><!--">--><?php //$comments->author(false); ?><!--</a>: --><?php //$comments->excerpt(35, '...'); ?><!--</li>-->
<!--                --><?php //endwhile; ?>
            </ul>
        </section>
<!--    --><?php //endif; ?>

<!--    --><?php //if (!empty($this->options->sidebarBlock) && in_array('ShowCategory', $this->options->sidebarBlock)): ?>
        <section class="widget">
            <h3 class="widget-title">分类</h3>
<!--            --><?php //$this->widget('Widget_Metas_Category_List')->listCategories('wrapClass=widget-list'); ?>
        </section>
<!--    --><?php //endif; ?>

<!--    --><?php //if (!empty($this->options->sidebarBlock) && in_array('ShowArchive', $this->options->sidebarBlock)): ?>
        <section class="widget">
            <h3 class="widget-title">归档</h3>
            <ul class="widget-list">
<!--                --><?php //$this->widget('Widget_Contents_Post_Date', 'type=month&format=F Y')
//                    ->parse('<li><a href="{permalink}">{date}</a></li>'); ?>
            </ul>
        </section>
<!--    --><?php //endif; ?>

<!--    --><?php //if (!empty($this->options->sidebarBlock) && in_array('ShowOther', $this->options->sidebarBlock)): ?>
        <section class="widget">
            <h3 class="widget-title">其它</h3>
            <ul class="widget-list">
<!--                --><?php //if($this->user->hasLogin()): ?>
                    <li class="last">
                        <a href="#">进入后台</a>
                    </li>
                    <li><a href="#">退出</a></li>
<!--                --><?php //else: ?>
                    <li class="last"><a href="#">登录</a></li>
<!--                --><?php //endif; ?>
                <li><a href="#">文章 RSS</a></li>
                <li><a href="#">评论 RSS</a></li>
                <li><a href="http://www.typecho.org">Typecho</a></li>
            </ul>
        </section>
<!--    --><?php //endif; ?>

</div><!-- end #sidebar -->
